# Generated by Django 4.2.11 on 2024-06-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intercambiar_puntos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
