# Generated by Django 5.0.4 on 2024-05-30 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0007_alter_producto_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trueque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado - como nuevo', 'Usado - Como nuevo'), ('usado - muy bueno', 'Usado - Muy bueno'), ('usado - bueno', 'Usado - Bueno'), ('usado - aceptable', 'Usado - Aceptable')], default='Nuevo', max_length=20)),
                ('descripcion', models.TextField(max_length=500)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.categoria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trueques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
