# Generated by Django 5.0.6 on 2024-06-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trueques', '0002_trueque_estado_trueque'),
        ('Trueques', '0003_alter_trueque_categoria_delete_categoria'),
    ]

    operations = [
    ]
