# Generated by Django 5.0.4 on 2024-06-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueques', '0005_alter_trueque_categoria_alter_trueque_estado_trueque'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntercambioTrueque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('trueque_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambio_1', to='Trueques.trueque')),
                ('trueque_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambio_2', to='Trueques.trueque')),
            ],
        ),
    ]
