# Generated by Django 5.0.4 on 2024-06-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueques', '0006_intercambiotrueque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambiotrueque',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Completado', 'Completado'), ('Rechazado', 'Rechazado'), ('Eliminado', 'Eliminado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='trueque',
            name='estado_trueque',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Eliminado', 'Eliminado'), ('Completado', 'Completado')], default='Pendiente', max_length=20),
        ),
    ]
