# Generated by Django 5.0.4 on 2024-06-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueques', '0009_alter_intercambiotrueque_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambiotrueque',
            name='codigo_usuario_producto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intercambiotrueque',
            name='codigo_usuario_trueque',
            field=models.IntegerField(default=0),
        ),
    ]
