# Generated by Django 5.0.4 on 2024-06-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueques', '0010_intercambiotrueque_codigo_usuario_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambiotrueque',
            name='codigo_usuario_producto',
            field=models.CharField(default='', max_length=20),
        ),
    ]
