# Generated by Django 4.2.11 on 2024-06-12 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trueques', '0011_alter_intercambiotrueque_codigo_usuario_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('filial', models.CharField(max_length=100)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dia', 'filial', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='intercambiotrueque',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trueques.turno'),
        ),
    ]
