# Generated by Django 4.2.11 on 2024-06-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trueques', '0012_turno_intercambiotrueque_turno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
    ]
