# Generated by Django 4.2.11 on 2024-07-03 01:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trueques', '0013_alter_turno_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('dia', 'filial', 'usuario')},
        ),
    ]
