# Generated by Django 5.0.6 on 2024-06-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueques', '0013_alter_turno_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='trueque',
            name='no_fue',
            field=models.BooleanField(default=True),
        ),
    ]
