# Generated by Django 5.0.6 on 2024-06-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueques', '0014_trueque_no_fue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trueque',
            name='no_fue',
        ),
        migrations.AddField(
            model_name='intercambiotrueque',
            name='no_fue',
            field=models.BooleanField(default=True),
        ),
    ]
