# Generated by Django 5.0.6 on 2024-07-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueques', '0015_remove_trueque_no_fue_intercambiotrueque_no_fue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intercambiotrueque',
            old_name='no_fue',
            new_name='no_fue_producto',
        ),
        migrations.AddField(
            model_name='intercambiotrueque',
            name='no_fue_trueque',
            field=models.BooleanField(default=True),
        ),
    ]
