# Generated by Django 5.0.6 on 2024-07-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueques', '0016_rename_no_fue_intercambiotrueque_no_fue_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercambiotrueque',
            name='no_fue_producto',
        ),
        migrations.RemoveField(
            model_name='intercambiotrueque',
            name='no_fue_trueque',
        ),
        migrations.AddField(
            model_name='intercambiotrueque',
            name='fue_producto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intercambiotrueque',
            name='fue_trueque',
            field=models.BooleanField(default=False),
        ),
    ]
