# Generated by Django 4.2.11 on 2024-07-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trueques', '0014_alter_turno_unique_together'),
        ('Trueques', '0017_remove_intercambiotrueque_no_fue_producto_and_more'),
    ]

    operations = [
    ]
