# Generated by Django 4.2.11 on 2024-07-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filiales', '0008_remove_filial_latitud_remove_filial_longitud'),
        ('Trueques', '0018_merge_20240703_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambiotrueque',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Completado', 'Completado'), ('Rechazado', 'Rechazado'), ('Espera de confirmacion', 'Espera de confirmacion'), ('Espera de confirmacion', 'Espera de confirmacion'), ('Eliminado', 'Eliminado')], default='Espera de confirmacion', max_length=30),
        ),
        migrations.AlterField(
            model_name='turno',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Filiales.filial'),
        ),
    ]
