# Generated by Django 5.0.6 on 2024-05-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('num', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('password', models.CharField(max_length=15)),
                ('bloqueado', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
