# Generated by Django 4.2.11 on 2024-06-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
