# Generated by Django 4.2.11 on 2024-07-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pantalla_principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
