# Generated by Django 5.0.4 on 2024-05-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dni',
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
