# Generated by Django 4.2.11 on 2024-05-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filiales', '0002_alter_filial_direccion'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudante',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Filiales.filial'),
        ),
        migrations.DeleteModel(
            name='Filial',
        ),
    ]
