# Generated by Django 4.2.11 on 2024-05-15 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ayudante_filial_delete_filial'),
        ('accounts', '0005_alter_usuario_username'),
    ]

    operations = [
    ]
