# Generated by Django 5.0.4 on 2024-05-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
