# Generated by Django 5.0.6 on 2024-05-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_block_alter_usuario_dni'),
        ('accounts', '0006_merge_20240514_2311'),
    ]

    operations = [
    ]
