# Generated by Django 4.2.11 on 2024-05-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usuario_blocked'),
        ('accounts', '0008_alter_usuario_dni'),
    ]

    operations = [
    ]
