# Generated by Django 5.0.4 on 2024-05-21 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filiales', '0002_alter_filial_direccion'),
        ('accounts', '0009_merge_0006_usuario_blocked_0008_alter_usuario_dni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='block',
        ),
        migrations.AddField(
            model_name='usuario',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Filiales.filial'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_ayudante',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Ayudante',
        ),
    ]
