# Generated by Django 4.2.11 on 2024-05-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_0006_usuario_blocked_0008_alter_usuario_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='usuario',
            name='profile_picture_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
