# Generated by Django 4.2.11 on 2024-05-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_usuario_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
