# Generated by Django 4.2.11 on 2024-05-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_administrador_remove_usuario_block_and_more'),
        ('accounts', '0011_usuario_profile_picture'),
    ]

    operations = [
    ]
