# Generated by Django 4.2.11 on 2024-05-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_usuario_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='profile_picture',
        ),
    ]
