# Generated by Django 5.0.4 on 2024-05-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_usuario_profile_picture_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
