# Generated by Django 5.0.4 on 2024-05-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_usuario_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
