# Generated by Django 5.0.4 on 2024-05-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_usuario_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
