# Generated by Django 5.0.4 on 2024-05-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_usuario_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estrellas',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puntos',
            field=models.IntegerField(default=100),
        ),
    ]
