# Generated by Django 4.2.11 on 2024-06-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_usuario_estrellas_usuario_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
