# Generated by Django 4.2.11 on 2024-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_usuario_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
