# Generated by Django 4.2.11 on 2024-06-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_usuario_borrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='borrado',
        ),
    ]
