# Generated by Django 4.2.11 on 2024-06-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_usuario_borrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cant_resenias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estrellas_totales',
            field=models.IntegerField(default=5),
        ),
    ]
