# Generated by Django 4.2.11 on 2024-06-25 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trueques', '0012_turno_intercambiotrueque_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField()),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trueques.intercambiotrueque')),
            ],
        ),
    ]
