# Generated by Django 5.0.6 on 2024-07-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reseñas', '0003_review_user_reseniado_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
    ]
