# Generated by Django 4.2.11 on 2024-05-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
