# Generated by Django 4.2.11 on 2024-05-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_rename_nombre_categoria_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
