# Generated by Django 4.2.11 on 2024-05-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_rename_foto_producto_foto_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('usado - como nuevo', 'Usado - Como nuevo'), ('usado - muy bueno', 'Usado - Muy bueno'), ('usado - bueno', 'Usado - Bueno'), ('usado - aceptable', 'Usado - Aceptable')], default='Nuevo', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
