# Generated by Django 4.2.11 on 2024-05-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_producto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=15),
        ),
    ]
