# Generated by Django 5.0.4 on 2024-05-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_alter_producto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
