# Generated by Django 5.0.4 on 2024-05-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_alter_producto_foto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='puntos',
            field=models.IntegerField(default=100),
        ),
    ]
