# Generated by Django 4.2.11 on 2024-06-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0009_categoria_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
