# Generated by Django 4.2.11 on 2024-06-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_categoria_borrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
