# Generated by Django 4.2.11 on 2024-07-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0011_producto_borrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='motivo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
