# Generated by Django 4.2.11 on 2024-05-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='direccion',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
