# Generated by Django 5.0.6 on 2024-05-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filiales', '0003_filial_id_ayudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='id_ayudante',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
