# Generated by Django 5.0.6 on 2024-05-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filiales', '0004_alter_filial_id_ayudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='id_ayudante',
            field=models.IntegerField(default=0),
        ),
    ]
