# Generated by Django 4.2.11 on 2024-06-10 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Filiales', '0005_alter_filial_id_ayudante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='id_ayudante',
        ),
        migrations.AddField(
            model_name='filial',
            name='ayudante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiales_ayudadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filial',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
