# Generated by Django 4.2.11 on 2024-06-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filiales', '0006_remove_filial_id_ayudante_filial_ayudante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='latitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='filial',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='filial',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
