# Generated by Django 4.2.11 on 2024-06-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filiales', '0007_filial_latitud_filial_longitud_filial_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='longitud',
        ),
    ]
